In [2]:
import numpy as np

In [35]:
a=np.arange(24).reshape((-1,2),order="F")
a

array([[ 0, 12],
       [ 1, 13],
       [ 2, 14],
       [ 3, 15],
       [ 4, 16],
       [ 5, 17],
       [ 6, 18],
       [ 7, 19],
       [ 8, 20],
       [ 9, 21],
       [10, 22],
       [11, 23]])

In [14]:
a[:,1:3]

array([[[ 2,  3],
        [ 4,  5]],

       [[10, 11],
        [12, 13]],

       [[18, 19],
        [20, 21]]])

In [40]:
a[::-2,0]

array([11,  9,  7,  5,  3,  1])

In [42]:
b=np.arange(0,36,2)
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34])

In [49]:
l=[1,2,3,4]
l


[1, 2, 3, 4]

TypeError: can only concatenate list (not "int") to list

In [50]:
for i in range(len(l)):
    l[i]=l[i]+5
l

[6, 7, 8, 9]

In [52]:
m=np.array([1,2,3,4])

In [55]:
np.any(m)

True

In [57]:
np.sum(np.any(m))

1

In [58]:
np.all(m)

True

In [60]:
m[m>0]

array([1, 2, 3, 4])

In [61]:
m[m is False]

array([], shape=(0, 4), dtype=int32)

In [67]:
arr = np.array([[3,3,3],[4,4,4],[5,5,5]])
brr = np.array([1,2,3])
subt = np.subtract(arr,brr.T)  # write your code here 
print(arr)
print(brr)
print(brr.T)
subt

[[3 3 3]
 [4 4 4]
 [5 5 5]]
[1 2 3]
[1 2 3]


array([[2, 1, 0],
       [3, 2, 1],
       [4, 3, 2]])

In [69]:
arr = np.array([2, 6, 1, 9, 10, 3, 27])
ans = arr[(arr>5)&(arr<10)]
ans

array([6, 9])

In [73]:
arr = np.arange(10, 34, 1).reshape(8,3) #write reshape code
ans = np.split(arr,3,axis=1)
print(arr)
ans

[[10 11 12]
 [13 14 15]
 [16 17 18]
 [19 20 21]
 [22 23 24]
 [25 26 27]
 [28 29 30]
 [31 32 33]]


[array([[10],
        [13],
        [16],
        [19],
        [22],
        [25],
        [28],
        [31]]),
 array([[11],
        [14],
        [17],
        [20],
        [23],
        [26],
        [29],
        [32]]),
 array([[12],
        [15],
        [18],
        [21],
        [24],
        [27],
        [30],
        [33]])]

In [75]:
x = np.array([[1], [2], [3]])
x.shape


(3, 1)

In [81]:
piaic = np.arange(100)
students = np.array([5,20,50,200,301,7001])
x = ( np.in1d( piaic, students) )
print(piaic)
print(students)
print(x)
x = np.sum( np.in1d( piaic, students) )
x

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[   5   20   50  200  301 7001]
[False False False False False  True False False False False False False
 False False False False False False False False  True False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False  True False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False]


3

In [82]:
piaic = np.arange(100)
students = np.array([True])
x = ( np.in1d( piaic, students) )
print(piaic)
print(students)
print(x)
x = np.sum( np.in1d( piaic, students) )
x

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ True]
[False  True False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False False False False False False False False False
 False False False False]


1

In [86]:
x = np.arange(1,11)
def abc(x):
    return x*2+3-2

abc(x)

array([ 3,  5,  7,  9, 11, 13, 15, 17, 19, 21])